TarefaWeb/Models/Tarefa.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace TarefaWeb.Models
{
    using inteiro = System.Int32;

    public class Tarefa
    {
        public int TarefaId { get; set; }

        [Required(ErrorMessage = "Por favor, preencha a descrição de sua tarefa")]
        [Display(Name ="Descrição")]
        public string Nome { get; set; }

        public bool Concluida { get; set; } = false;

        public DateTime Data { get; set; }
    }
}

TarefaWeb/Models/TarefaModel.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;

namespace TarefaWeb.Models
{
    public class Model : IDisposable
    {
        protected SqlConnection conn;

        public Model()
        {
            string strConn = @"Data Source=localhost;
                                Initial Catalog=BDTarefa;
                                Integrated Security=true";
                            // User Id = sa; Password=dba;

            conn = new SqlConnection(strConn);
            conn.Open();
        }

        public void Dispose()
        {
            conn.Close();
        }
    }

    public class TarefaModel : Model
    {
        public List<Tarefa> Read()
        {
            List<Tarefa> lista = new List<Tarefa>();

            SqlCommand cmd = new SqlCommand();
            cmd.Connection = conn;
            cmd.CommandText = @"SELECT * 
                                FROM Tarefa";

            SqlDataReader reader = cmd.ExecuteReader();

            while(reader.Read())
            {
                Tarefa t = new Tarefa
                {
                    TarefaId = reader.GetInt32(0),
                    Nome = reader.GetString(1),
                    Concluida = (bool)reader["Concluida"],
                    Data = (DateTime)reader["Data"]
                };

                lista.Add(t);
            }

            return lista;
        }

        public void Create(Tarefa t)
        {
            SqlCommand cmd = new SqlCommand();
            cmd.Connection = conn;
            cmd.CommandText = "INSERT INTO Tarefa VALUES (@nome, @concluida, @data)";

            cmd.Parameters.AddWithValue("@nome", t.Nome);
            cmd.Parameters.AddWithValue("@concluida", t.Concluida);
            cmd.Parameters.AddWithValue("@data", t.Data);

            cmd.ExecuteNonQuery();
        }

        public void Update(Tarefa t)
        {
            SqlCommand cmd = new SqlCommand();
            cmd.Connection = conn;
            cmd.CommandText = @"UPDATE Tarefa SET Nome = @nome, Concluida = @concluida
                                    WHERE TarefaId = @id";

            cmd.Parameters.AddWithValue("@nome", t.Nome);
            cmd.Parameters.AddWithValue("@concluida", t.Concluida);
            cmd.Parameters.AddWithValue("@id", t.TarefaId);

            cmd.ExecuteNonQuery();
        }

        public void Delete(int id)
        {
            SqlCommand cmd = new SqlCommand();
            cmd.Connection = conn;
            cmd.CommandText = "DELETE FROM Tarefa WHERE TarefaId = @id";

            cmd.Parameters.AddWithValue("@id", id);

            cmd.ExecuteNonQuery();
        }

        public Tarefa Read(int id)
        {
            Tarefa t = null;

            SqlCommand cmd = new SqlCommand();
            cmd.Connection = conn;
            cmd.CommandText = @"SELECT * FROM Tarefa
                                WHERE TarefaId = @id";

            cmd.Parameters.AddWithValue("@id", id);

            SqlDataReader reader = cmd.ExecuteReader();

            if (reader.Read())
            {
                t = new Tarefa
                {
                    TarefaId = reader.GetInt32(0),
                    Nome = reader.GetString(1),
                    Concluida = (bool)reader["Concluida"],
                    Data = (DateTime)reader["Data"]
                };
            }

            return t;
        }
    }
}

TarefaWeb/Controllers/TarefaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TarefaWeb.Models;

namespace TarefaWeb.Controllers
{
    public class TarefaController : Controller
    {
        [HttpGet]
        // GET: Tarefa
        public ActionResult Index()
        {
            using (TarefaModel model = new TarefaModel())
            {
                List<Tarefa> lista = model.Read();                
                return View(lista);

            } //model.Dispose();
        }

        public JsonResult Lista()
        {
            using (TarefaModel model = new TarefaModel())
                return Json(model.Read(), JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Tarefa t)
        {
            if (ModelState.IsValid)
            {
                t.Concluida = false;
                t.Data = DateTime.Now;

                using (TarefaModel model = new TarefaModel())
                {
                    model.Create(t);
                    return RedirectToAction("Index");
                }
            }
            else
            {
                ViewBag.Erro = "Preencha a descrição da tarefa.";
                return View();
            }
        }

        public ActionResult Update(int id)
        {
            using(TarefaModel model = new TarefaModel())
            {
                return View(model.Read(id));
            }
        }

        [HttpPost]
        public ActionResult Update(int id, Tarefa t)
        {
            if(ModelState.IsValid)
            {
                using(TarefaModel model = new TarefaModel())
                {
                    model.Update(t);
                    return RedirectToAction("Index");
                }
            }
            else
            {
                return View(t);
            }
        }

        public ActionResult Delete(int id)
        {
            using(TarefaModel model = new TarefaModel())
            {
                model.Delete(id);
                return RedirectToAction("Index");
            }
        }
    }
}

TarefaWeb/Controllers/TarefasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using TarefaWeb.Models;

namespace TarefaWeb.Controllers
{
    public class TarefasController : ApiController
    {
        public List<Tarefa> Get()
        {
            using(TarefaModel model = new TarefaModel())
            {
                return model.Read();
            }
        }

        public HttpResponseMessage Post([FromBody]Tarefa t)
        {
            if (ModelState.IsValid)
            {
                using (TarefaModel model = new TarefaModel())
                {
                    t.Data = DateTime.Now;
                    model.Create(t);
                    return Request.CreateResponse(HttpStatusCode.OK, "Cadastrado com sucesso");
                }
            }
            else
            {
                return Request.CreateResponse(HttpStatusCode.PreconditionFailed, ModelState.Values);
            }
        }

        public Tarefa Get(int id)
        {
            using(TarefaModel model = new TarefaModel())
            {
                return model.Read(id);
            }
        }

        [HttpGet]
        [Route("api/tarefas/obtem/{id}")]
        public Tarefa Obtem(int id)
        {
            using (TarefaModel model = new TarefaModel())
            {
                return model.Read(id);
            }
        }
    }
}

TarefaWeb/Views/Tarefa/Create.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <title>Create</title>
</head>
<body>

    @if (ViewBag.Erro != null)
    {
    <div class="alert alert-danger">
        @ViewBag.Erro
    </div>
    }

    <form action="/Tarefa/Create" method="post">

        <div class="form-group">
            <label>Descrição</label>
            <input type="text" name="Nome" class="form-control"/>
        </div>

        <button class="btn btn-primary">Salvar</button>
    </form>
</body>
</html>

TarefaWeb/Views/Tarefa/Index.cshtml
@model IEnumerable<TarefaWeb.Models.Tarefa>
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <table>
        @foreach (var t in Model)
        {
        <tr>
            <td>@t.TarefaId</td>
            <td>@t.Nome</td>
            <td>@t.Concluida</td>
            <td>@t.Data</td>
            <td>@Html.ActionLink("Editar", "Update", new { id = t.TarefaId })</td>
            <td>
                <a href="/Tarefa/Delete/@t.TarefaId">Apagar</a>
            </td>
        </tr>
        }
    </table>

    <a href="/Tarefa/Create">Adicionar</a>
</body>
</html>

TarefaWeb/Views/Tarefa/Update.cshtml
@model TarefaWeb.Models.Tarefa
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <title>Update</title>
</head>
<body>
    @using (Html.BeginForm("Update", "Tarefa", FormMethod.Post))
    {
        @Html.HiddenFor(m => m.TarefaId)

        <div class="form-group">
            @Html.DisplayNameFor(m => m.Nome)
            @Html.TextBoxFor(m => m.Nome, new {@class = "form-control"})
            @Html.ValidationMessageFor(m => m.Nome)
        </div>

        <div class="form-group">
            @Html.DisplayNameFor(m => m.Concluida)
            @Html.CheckBoxFor(m => m.Concluida)
        </div>   
        
        <div class="form-group">
            @Html.DisplayNameFor(m => m.Data)
            @Html.TextBoxFor(m => m.Data, new {@type = "date" })
        </div>

        <button class="btn btn-primary">Salvar</button>
    }
</body>
</html>